### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by atymic** [laravel-notification-channels/jusibe#9]
Hi @unicodeveloper 

Are you still maintaining this channel?
If so, could you update it support later versions for PHP/Laravel (5.5 - 6.0)?

Thanks

**Comment by atymic** [comment]
cc @unicodeveloper

**Comment by unicodeveloper** [comment]
@atymic Yes I still do. Thanks for the reminder. Will do this weekend

**Comment by atymic** [comment]
Thanks Mate :)

**Comment by atymic** [comment]
Sorry to bug you @unicodeveloper but are you still planning on updating the package? Thanks :)

**Comment by unicodeveloper** [comment]
@atymic I just updated it. Thanks for your persistence!
